version: "3.8"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: netdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build: .
    depends_on:
      - db
    environment:
      PG_DB: netdb
      PG_USER: admin
      PG_PASS: admin
      PG_HOST: db
      PG_PORT: 5432
    ports:
      - "5001:5001"
    volumes:
      - .:/app
    command: python anomaly_detector.py

volumes:
  pgdata:
